begin;

create table if not exists public.prompt_categories (
  id bigint generated by default as identity primary key,
  medium text not null check (medium in ('Fotografi','Graphic','Ilustrasi')),
  name text not null,
  slug text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists prompt_categories_medium_name_unique
  on public.prompt_categories (medium, lower(name));
create unique index if not exists prompt_categories_medium_slug_unique
  on public.prompt_categories (medium, slug);
create index if not exists prompt_categories_active_sort_idx
  on public.prompt_categories (medium, is_active, sort_order, name);

alter table public.prompt_categories enable row level security;

drop policy if exists "Public read prompt categories" on public.prompt_categories;
drop policy if exists "Public read active prompt categories" on public.prompt_categories;
drop policy if exists "Admin read prompt categories" on public.prompt_categories;
drop policy if exists "Admin insert prompt categories" on public.prompt_categories;
drop policy if exists "Admin update prompt categories" on public.prompt_categories;
drop policy if exists "Admin delete prompt categories" on public.prompt_categories;

create policy "Public read active prompt categories"
  on public.prompt_categories for select
  using (is_active = true);

create policy "Admin read prompt categories"
  on public.prompt_categories for select
  to authenticated
  using (public.is_promptvault_admin());

create policy "Admin insert prompt categories"
  on public.prompt_categories for insert
  to authenticated
  with check (public.is_promptvault_admin());

create policy "Admin update prompt categories"
  on public.prompt_categories for update
  to authenticated
  using (public.is_promptvault_admin())
  with check (public.is_promptvault_admin());

create policy "Admin delete prompt categories"
  on public.prompt_categories for delete
  to authenticated
  using (public.is_promptvault_admin());

grant select on public.prompt_categories to anon, authenticated;
grant insert, update, delete on public.prompt_categories to authenticated;
grant usage, select on sequence public.prompt_categories_id_seq to authenticated;

insert into public.prompt_categories (medium, name, slug, sort_order)
select
  p.medium,
  btrim(p.category),
  lower(regexp_replace(regexp_replace(btrim(p.category), '[^a-zA-Z0-9]+', '-', 'g'), '(^-|-$)', '', 'g')),
  row_number() over (partition by p.medium order by count(*) desc, btrim(p.category))::integer
from public.prompts p
where p.medium in ('Fotografi','Graphic','Ilustrasi')
  and coalesce(btrim(p.category),'') <> ''
group by p.medium, btrim(p.category)
on conflict do nothing;

commit;
